[package]
name = "data-cube"
description = "Small crate to create and work with threedimensional arrays"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["data", "array", "cube", "threedimensional"]

[dependencies]

[lib]
name= "data-cube"
path = "src/lib.rs"

